const DATE_FORMAT = 'DD-MM-YYYY'
const DATE_FORMAT_2 = 'DD/MM/YYYY'
const DATE_TIME_FORMAT = 'YYYY-MM-DD hh:mmA'
const DATE_PICKER_FORMAT = 'YYYY-MM-DD'
const DATE_TIME_PICKER_FORMAT = 'YYYY-MM-DD hh:mmA'
const DATE_IOS_FORMAT = 'MM-DD-YYYY'
const DATE_FORMAT_MOOD = 'DD/MM/YYYY hh:mm:ssA'
const DATE_FORMAT_DO = 'MMM Do YY'

export {
  DATE_FORMAT,
  DATE_FORMAT_2,
  DATE_FORMAT_DO,
  DATE_FORMAT_MOOD,
  DATE_IOS_FORMAT,
  DATE_PICKER_FORMAT,
  DATE_TIME_FORMAT,
  DATE_TIME_PICKER_FORMAT,
}
